import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { checkTop3, datasetDraws, tb9Fixed, verifiedSelection, evaluateMonth, canonicalSource, CANCELED, type Draw } from "../src/lib/lottery/tb9-fixed";

const rows: Draw[] = Array.from({ length: 365 }, (_, i) => ({ date: new Date(Date.UTC(2023, 0, i + 1)).toISOString().slice(0, 10), top2: String(i % 100).padStart(2, "0") })).filter((r) => !CANCELED.has(r.date));
const selection = verifiedSelection(rows, "2024-01");
assert.equal(selection.audit.length, 100);
assert.equal(selection.audit.filter((a) => a.group === "top").length, 34);
assert.equal(selection.audit.filter((a) => a.group === "mid").length, 33);
assert.equal(selection.audit.filter((a) => a.group === "bottom").length, 33);
assert(selection.candidate_count >= 45 && selection.candidate_count <= 67);
assert.equal(selection.training_start, "2023-04-01");
assert.deepEqual(selection, verifiedSelection([...rows, { date: "2024-01-01", top2: "99" }], "2024-01"));
assert.equal(canonicalSource(rows, "2024-01"), canonicalSource([...rows].reverse(), "2024-01"));
assert.equal(canonicalSource(rows, "2024-01"), canonicalSource([...rows, {date:"2024-01-01",top2:"99"}], "2024-01"));
assert.throws(() => verifiedSelection(rows.slice(1), "2024-01"), /ประวัติยังไม่ครบ/);
assert.throws(() => tb9Fixed([...rows, rows[0]], "2024-01"), /ซ้ำ/);
assert.throws(() => tb9Fixed([{ date: "2023-01-01", top2: "1" }], "2024-01"), /ไม่ถูกต้อง/);
assert.throws(() => tb9Fixed(rows, "2024-13"));
const unseen = tb9Fixed(rows.map((r) => ({ ...r, top2: "00" })), "2024-01").audit.find((a) => a.number === "99")!;
assert.equal(unseen.gap_is_lower_bound, true); assert.equal(unseen.gap, rows.length);
assert.equal(selection.audit.find((a) => a.number === rows.at(-1)!.top2)!.gap, 0);
const example = { ...selection, candidate_count: 52, candidates: Array.from({ length: 52 }, (_, i) => String(i).padStart(2,"0")) };
for (const [hits, expected] of [[15, -60], [16, 40]]) {
  const result = evaluateMonth(example, Array.from({ length: 30 }, (_, i) => ({ date: `2024-01-${String(i+1).padStart(2,"0")}`, top2: i < hits ? "00" : "99" })));
  assert.equal(result.profit, expected);
}
assert.throws(() => evaluateMonth(selection, [], 0));
assert.throws(() => datasetDraws([{ year: "66", digits: 2, is_date_sorted: false, sequence: "00" }]));
assert.equal(checkTop3([{ date: "2023-01-01", top2: "23" }], [{ year: "66", digits: 3, is_date_sorted: true, sequence: "123" }]), 1);
assert.throws(() => checkTop3([{ date: "2023-01-01", top2: "24" }], [{ year: "66", digits: 3, is_date_sorted: true, sequence: "123" }]), /ไม่ตรง/);

// Optional independent goldens generated by the user's unmodified Python function.
if (process.argv[2]) {
  const cases = JSON.parse(readFileSync(process.argv[2], "utf8"));
  for (const c of cases) {
    const actual = tb9Fixed(c.rows, c.month);
    const audit = Object.fromEntries(actual.audit.map(({number, ...a}) => [number, a]));
    assert.deepEqual({ ...actual, audit }, c.expected);
  }
  console.log(`Python parity: ${cases.length} cases, including every audit field of all 100 numbers`);
}
if (process.argv[3]) {
  const actualRows = datasetDraws(JSON.parse(readFileSync(process.argv[3], "utf8")));
  const sept = verifiedSelection(actualRows, "2026-09");
  const total = { days: 0, wins: 0, cost: 0, profit: 0 };
  for (let y = 2024; y <= 2026; y++) for (let m = 1; m <= 12; m++) {
    const month = `${y}-${String(m).padStart(2,"0")}`; if (month > "2026-08") continue;
    const r = evaluateMonth(verifiedSelection(actualRows, month), actualRows);
    total.days += r.draws.length; total.wins += r.wins; total.cost += r.cost; total.profit += r.profit;
  }
  console.log(JSON.stringify({ september: sept.candidates, n: sept.candidate_count, training: sept.training_draws, number21: sept.audit.find((a) => a.number === "21"), total, roi: total.profit / total.cost * 100 }, null, 2));
}
console.log("TB9 boundary checks passed");
